trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: complex_model_m
  parameterServerType: large_model
  workerCount: 5
  parameterServerCount: 2
  args:
    /b/modified-mnist-bucket/o/train_y.csv
